#!/bin/sh

PATH="/home/jesusda91/wordpress-4.9.8-0/apps/wordpress/bin:/home/jesusda91/wordpress-4.9.8-0/varnish/bin:/home/jesusda91/wordpress-4.9.8-0/sqlite/bin:/home/jesusda91/wordpress-4.9.8-0/php/bin:/home/jesusda91/wordpress-4.9.8-0/mysql/bin:/home/jesusda91/wordpress-4.9.8-0/apache2/bin:/home/jesusda91/wordpress-4.9.8-0/common/bin:$PATH"
BITNAMI_ROOT="/home/jesusda91/wordpress-4.9.8-0"
export BITNAMI_ROOT


exec /usr/bin/zsh --no-globalrcs --no-rcs
