#!/bin/sh

. /home/jesusda91/wordpress-4.9.8-0/scripts/setenv.sh
SASL_PATH="/home/jesusda91/wordpress-4.9.8-0/common/lib/sasl2"
                export SASL_PATH
exec /home/jesusda91/wordpress-4.9.8-0/common/sbin/.sasldblistusers2.bin -f "/home/jesusda91/wordpress-4.9.8-0/common/etc/sasldb2" "$@"
